spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  datasource:
    writer:
      jdbc-url: jdbc:postgresql://nas.codegurus.co.kr:5432/strapi
      username: strapi
      password: strapi12!@QW
      platform: postgres
    reader:
      jdbc-url: jdbc:postgresql://nas.codegurus.co.kr:5432/strapi
      username: strapi
      password: strapi12!@QW
      platform: postgres
  servlet:
    multipart:
      max-file-size: 4024KB
      max-request-size: 4024KB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
#  redis:
#    host: localhost
#    port: 6379

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret-key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  algorithm: HS256

server:
  port: 8082
