### 직접 JSON 사용
POST http://localhost:8082/api/v1/posts
Content-Type: application/json

{
  "id": 1,
  "title": "testtitle",
  "body": "testbody"

}


### GET
GET http://localhost:8082/api/v1/users/1

